version: '3.0'
services:
  development-database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5430:5432"
    volumes:
      - "postgres_volume:/var/lib/postgresql/data"

volumes:
  postgres_volume: